#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-MRO-Compat
Version  : 0.12
Release  : 5
URL      : http://search.cpan.org/CPAN/authors/id/B/BO/BOBTFISH/MRO-Compat-0.12.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/B/BO/BOBTFISH/MRO-Compat-0.12.tar.gz
Summary  : 'mro::* interface compatibility for Perls < 5.9.5'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-MRO-Compat-doc
BuildRequires : perl(inc::Module::Install)

%description
NAME
MRO::Compat - mro::* interface compatibility for Perls < 5.9.5
SYNOPSIS
package PPP;      use base qw/Exporter/;
package X;        use base qw/PPP/;
package Y;        use base qw/PPP/;
package Z;        use base qw/PPP/;

%package doc
Summary: doc components for the perl-MRO-Compat package.
Group: Documentation

%description doc
doc components for the perl-MRO-Compat package.


%prep
%setup -q -n MRO-Compat-0.12

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/MRO/Compat.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
